Curlyqueue: curlyqueue.c File Reference
curlyqueue.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "curlyqueue.h"
Functions
curlyqueue_node_t * curlyqueue_create_node (void *value, curlyqueue_node_t *prev, curlyqueue_node_t *next)
Creates new list node.
curlyqueue_t * curlyqueue_create_queue ()
Initializes the linked list manager struct.
void curlyqueue_destroy_queue (curlyqueue_t *queue)
Rolls through list, freeing resources.
void curlyqueue_enqueue (curlyqueue_t *queue, void *value)
Creates a node for a given value and adds it to the back of a queue.
void * curlyqueue_dequeue (curlyqueue_t *queue, except_t *e)
Pops value of front of q and returns a void pointer to it throws "empty_q" exception if q is empty.
int curlyqueue_is_empty (curlyqueue_t *queue)
A simple function that checks if a queue is empty or not.
void curlyqueue_iterator_jump_to_back (curlyqueue_t *queue)
Point the iterator at the back of the list.
void curlyqueue_iterator_jump_to_front (curlyqueue_t *queue)
Point the iterator at the front of the list.
void curlyqueue_iterator_step_forward (curlyqueue_t *queue, except_t *e)
Advances the queue iterator forward one element.
void curlyqueue_iterator_step_backward (curlyqueue_t *queue, except_t *e)
Moves the iterator backward one item.
void * curlyqueue_get_value_at_iterator (curlyqueue_t *queue, except_t *e)
Gets the value at the point in the queue indicated by the iterator.
int curlyqueue_iterator_has_next (curlyqueue_t *queue, except_t *e)
Tests if the current list element pointed at by the iterator has an element after it.
int curlyqueue_iterator_has_prev (curlyqueue_t *queue, except_t *e)
Tests if the current list element pointed at by the iterator has an element before it.
void curlyqueue_insert_value_before_iterator (curlyqueue_t *queue, void *value, except_t *e)
Inserts a value into the q at the position before the node pointed at by the iter.
void curlyqueue_insert_value_after_iterator (curlyqueue_t *queue, void *value, except_t *e)
Insert the given value after the item pointed at by the q iterator.
void curlyqueue_delete_value_at_iterator (curlyqueue_t *queue, except_t *e)
Deletes the value pointed at by the iterator, removes the assoc node from the list, and deallocates memory.
Function Documentation
curlyqueue_node_t* curlyqueue_create_node (void * value, curlyqueue_node_t * prev, curlyqueue_node_t * next)
Creates new list node.
Precondition:
calling fn has determined prev and next pointers
Postcondition:
mem has been allocated for new node and and node field values have been assigned
Note:
calling fn must free mem!
Definition at line 14 of file curlyqueue.c.
References curlyqueue_node_t::next, curlyqueue_node_t::prev, and curlyqueue_node_t::value.
Referenced by curlyqueue_enqueue(), curlyqueue_insert_value_after_iterator(), and curlyqueue_insert_value_before_iterator().
curlyqueue_t* curlyqueue_create_queue ()
Initializes the linked list manager struct.
Postcondition:
mem has been allocated for queuea and field valies have been initialized to null (if pointers) or zero (if count)
Note:
calling fn must free mem!
Definition at line 32 of file curlyqueue.c.
References curlyqueue_t::back, curlyqueue_t::count, curlyqueue_t::front, curlyqueue_t::iterator, and NULL.
void curlyqueue_delete_value_at_iterator (curlyqueue_t * queue, except_t * e)
Deletes the value pointed at by the iterator, removes the assoc node from the list, and deallocates memory.
Exceptions:
null_iter if iterator is not set to an element
Definition at line 398 of file curlyqueue.c.
References curlyqueue_t::back, curlyqueue_t::count, curlyqueue_dequeue(), curlyqueue_iterator_jump_to_back(), curlyqueue_iterator_step_backward(), curlyqueue_t::front, curlyqueue_t::iterator, curlyqueue_node_t::next, NULL, curlyqueue_node_t::prev, except_t::thrown, and except_t::type.
void* curlyqueue_dequeue (curlyqueue_t * queue, except_t * e)
Pops value of front of q and returns a void pointer to it throws "empty_q" exception if q is empty.
Definition at line 124 of file curlyqueue.c.
References curlyqueue_t::back, curlyqueue_t::count, curlyqueue_is_empty(), curlyqueue_t::front, curlyqueue_node_t::next, NULL, curlyqueue_node_t::prev, except_t::thrown, except_t::type, and curlyqueue_node_t::value.
void curlyqueue_destroy_queue (curlyqueue_t * queue)
Rolls through list, freeing resources.
Parameters:
queue the q to destroy
Precondition:
the queue pointer is not NULL
Postcondition:
all nodes in the list are freed
the list manager's pointers are set to null
the list manager's count is decremented for each freed node
the current node
the node after current node
Definition at line 52 of file curlyqueue.c.
References curlyqueue_t::back, curlyqueue_t::count, curlyqueue_node_t::next, and NULL.
void curlyqueue_enqueue (curlyqueue_t * queue, void * value)
Creates a node for a given value and adds it to the back of a queue.
Parameters:
queue The queue to add the value to
value The value to push onto the q
Postcondition:
The queue's count is incremented
Iterator is set to queue->back (to remove the need for remembering if the iter was initalized or not,ie to avoid the possibility of a null iter if there are items in list)
Definition at line 93 of file curlyqueue.c.
References curlyqueue_t::back, curlyqueue_t::count, curlyqueue_create_node(), curlyqueue_is_empty(), curlyqueue_iterator_jump_to_back(), curlyqueue_t::front, NULL, and curlyqueue_node_t::prev.
void* curlyqueue_get_value_at_iterator (curlyqueue_t * queue, except_t * e)
Gets the value at the point in the queue indicated by the iterator.
Definition at line 233 of file curlyqueue.c.
References curlyqueue_t::iterator, NULL, except_t::thrown, except_t::type, and curlyqueue_node_t::value.
void curlyqueue_insert_value_after_iterator (curlyqueue_t * queue, void * value, except_t * e)
Insert the given value after the item pointed at by the q iterator.
Definition at line 350 of file curlyqueue.c.
References curlyqueue_t::count, curlyqueue_create_node(), curlyqueue_t::front, curlyqueue_t::iterator, curlyqueue_node_t::next, NULL, curlyqueue_node_t::prev, except_t::thrown, and except_t::type.
void curlyqueue_insert_value_before_iterator (curlyqueue_t * queue, void * value, except_t * e)
Inserts a value into the q at the position before the node pointed at by the iter.
Postcondition:
Mem has been allocated for a new node
a node was created,and the value is now in queue
the q iter points at the enew node
Note:
The calling function is responsible for freeing the memory allocated
Exceptions:
null_iter if iter is null
Definition at line 313 of file curlyqueue.c.
References curlyqueue_t::back, curlyqueue_t::count, curlyqueue_create_node(), curlyqueue_enqueue(), curlyqueue_t::iterator, curlyqueue_node_t::next, NULL, curlyqueue_node_t::prev, except_t::thrown, and except_t::type.
int curlyqueue_is_empty (curlyqueue_t * queue)
A simple function that checks if a queue is empty or not.
Parameters:
queue The queue to check.
Returns:
1, if the queue is empty
0 if not empty
Definition at line 168 of file curlyqueue.c.
References curlyqueue_t::count.
int curlyqueue_iterator_has_next (curlyqueue_t * queue, except_t * e)
Tests if the current list element pointed at by the iterator has an element after it.
Exceptions:
empty_q if queue is empty
null_iter if iterator is null (use iter_reset to fix if q is non-empty)
Returns:
0 if queue does not have next
1 if queue does have next
See also:
curlyqueue_iterator_has_prev
Definition at line 254 of file curlyqueue.c.
References curlyqueue_is_empty(), curlyqueue_t::iterator, curlyqueue_node_t::next, NULL, except_t::thrown, and except_t::type.
int curlyqueue_iterator_has_prev (curlyqueue_t * queue, except_t * e)
Tests if the current list element pointed at by the iterator has an element before it.
Exceptions:
empty_q if queue is empty
null_iter if iterator is null (use iter_reset to fix if q is non-empty)
Returns:
0 if queue does not have prev
1 if queue does have prev
See also:
curlyqueue_iterator_has_next
Definition at line 284 of file curlyqueue.c.
References curlyqueue_is_empty(), curlyqueue_t::iterator, NULL, curlyqueue_node_t::prev, except_t::thrown, and except_t::type.
void curlyqueue_iterator_jump_to_back (curlyqueue_t * queue)
Point the iterator at the back of the list.
Definition at line 179 of file curlyqueue.c.
References curlyqueue_t::back, and curlyqueue_t::iterator.
void curlyqueue_iterator_jump_to_front (curlyqueue_t * queue)
Point the iterator at the front of the list.
Definition at line 186 of file curlyqueue.c.
References curlyqueue_t::front, and curlyqueue_t::iterator.
void curlyqueue_iterator_step_backward (curlyqueue_t * queue, except_t * e)
Moves the iterator backward one item.
Exceptions:
null_iter if q iterator is null, which can happen if it has not yet been init'd, or if q is empty
Definition at line 213 of file curlyqueue.c.
References curlyqueue_t::iterator, NULL, curlyqueue_node_t::prev, except_t::thrown, and except_t::type.
void curlyqueue_iterator_step_forward (curlyqueue_t * queue, except_t * e)
Advances the queue iterator forward one element.
Exceptions:
if iterator is currently pointing at NULL, i.e. trying to access iter->next would be bad
Definition at line 196 of file curlyqueue.c.
References curlyqueue_t::iterator, curlyqueue_node_t::next, NULL, except_t::thrown, and except_t::type.