Curly Queue: curlyqueue.h File Reference
curlyqueue.h File Reference
Declares functions and data structures implemented and used, respectively, in curlyqueue.c.
Data Structures
struct except_t
A datatype to help implement exception handling.
struct curlyqueue_t
The head, tail, and count of a queue.
struct curlyqueue_node_t
A node in a linked list.
Defines
#define NULL 0
Typedefs
typedef struct except_t except_t
typedef struct
curlyqueue_node_t curlyqueue_node_t
typedef struct
curlyqueue_t curlyqueue_t
Functions
curlyqueue_t * curlyqueue_create_queue ()
Initializes the linked list manager struct.
void curlyqueue_destroy_queue (curlyqueue_t *)
Rolls through list, freeing resources.
void curlyqueue_enqueue (curlyqueue_t *queue, void *value)
Creates a node for a given value and adds it to the back of a queue.
void * curlyqueue_dequeue (curlyqueue_t *queue, except_t *e)
Pops value of front of q and returns a void pointer to it.
int curlyqueue_is_empty (curlyqueue_t *)
A simple function that checks if a queue is empty or not.
int curlyqueue_iterator_has_next (curlyqueue_t *queue, except_t *e)
Tests if the current list element pointed at by the iterator has an element after it.
int curlyqueue_iterator_has_prev (curlyqueue_t *queue, except_t *e)
Tests if the current list element pointed at by the iterator has an element before it.
void curlyqueue_iterator_step_forward (curlyqueue_t *queue, except_t *e)
Advances the queue iterator forward one element.
void curlyqueue_iterator_step_backward (curlyqueue_t *queue, except_t *e)
Moves the iterator backward one item.
void curlyqueue_iterator_jump_to_front (curlyqueue_t *queue)
Point the iterator at the front of the list.
void curlyqueue_iterator_jump_to_back (curlyqueue_t *queue)
Point the iterator at the back of the list.
void * curlyqueue_get_value_at_iterator (curlyqueue_t *queue, except_t *e)
Gets the value at the point in the queue indicated by the iterator.
void curlyqueue_delete_value_at_iterator (curlyqueue_t *queue, except_t *e)
Deletes the value pointed at by the iterator, removes the assoc node from the list, and deallocates memory.
void curlyqueue_insert_value_before_iterator (curlyqueue_t *queue, void *value, except_t *e)
Inserts a value into the q at the position before the node pointed at by the iter.
void curlyqueue_insert_value_after_iterator (curlyqueue_t *queue, void *value, except_t *e)
Insert the given value after the item pointed at by the q iterator.
Detailed Description
Declares functions and data structures implemented and used, respectively, in curlyqueue.c.
Definition in file curlyqueue.h.
Define Documentation
#define NULL 0
Definition at line 9 of file curlyqueue.h.
Referenced by curlyqueue_create_queue(), curlyqueue_delete_value_at_iterator(), curlyqueue_dequeue(), curlyqueue_destroy_queue(), curlyqueue_enqueue(), curlyqueue_get_value_at_iterator(), curlyqueue_insert_value_after_iterator(), curlyqueue_insert_value_before_iterator(), curlyqueue_iterator_has_next(), curlyqueue_iterator_has_prev(), curlyqueue_iterator_step_backward(), and curlyqueue_iterator_step_forward().
Typedef Documentation
typedef struct curlyqueue_node_t curlyqueue_node_t
Definition at line 13 of file curlyqueue.h.
typedef struct curlyqueue_t curlyqueue_t
Definition at line 14 of file curlyqueue.h.
typedef struct except_t except_t
Definition at line 12 of file curlyqueue.h.
Function Documentation
curlyqueue_t* curlyqueue_create_queue ()
Initializes the linked list manager struct.
Postcondition:
Mem has been allocated for queuea and field valies have been initialized to null (if pointers) or zero (if count)
Note:
Calling fn must free mem!
Definition at line 36 of file curlyqueue.c.
void curlyqueue_delete_value_at_iterator (curlyqueue_t * queue, except_t * e)
Deletes the value pointed at by the iterator, removes the assoc node from the list, and deallocates memory.
Exceptions:
null_iter if iterator is not set to an element
Definition at line 398 of file curlyqueue.c.
void* curlyqueue_dequeue (curlyqueue_t * queue, except_t * e)
Pops value of front of q and returns a void pointer to it.
Exceptions:
empty_q exception if q is empty
Definition at line 122 of file curlyqueue.c.
Referenced by curlyqueue_delete_value_at_iterator().
void curlyqueue_destroy_queue (curlyqueue_t * queue)
Rolls through list, freeing resources.
Parameters:
queue the q to destroy
Precondition:
The queue pointer is not NULL
Postcondition:
All nodes in the list are freed
The list manager's pointers are set to null
The list manager's count is decremented for each freed node
Definition at line 56 of file curlyqueue.c.
void curlyqueue_enqueue (curlyqueue_t * queue, void * value)
Creates a node for a given value and adds it to the back of a queue.
Parameters:
queue The queue to add the value to
value The value to push onto the q
Postcondition:
The queue's count is incremented
Iterator is set to queue->back (to remove the need for remembering if the iter was initalized or not,ie to avoid the possibility of a null iter if there are items in list)
Definition at line 91 of file curlyqueue.c.
Referenced by curlyqueue_insert_value_before_iterator().
void* curlyqueue_get_value_at_iterator (curlyqueue_t * queue, except_t * e)
Gets the value at the point in the queue indicated by the iterator.
Definition at line 233 of file curlyqueue.c.
void curlyqueue_insert_value_after_iterator (curlyqueue_t * queue, void * value, except_t * e)
Insert the given value after the item pointed at by the q iterator.
Definition at line 350 of file curlyqueue.c.
void curlyqueue_insert_value_before_iterator (curlyqueue_t * queue, void * value, except_t * e)
Inserts a value into the q at the position before the node pointed at by the iter.
Postcondition:
Mem has been allocated for a new node
a node was created,and the value is now in queue
the q iter points at the enew node
Note:
The calling function is responsible for freeing the memory allocated
Exceptions:
null_iter if iter is null
Definition at line 313 of file curlyqueue.c.
int curlyqueue_is_empty (curlyqueue_t * queue)
A simple function that checks if a queue is empty or not.
Parameters:
queue The queue to check.
Returns:
1, if the queue is empty
0 if not empty
Definition at line 166 of file curlyqueue.c.
Referenced by curlyqueue_dequeue(), curlyqueue_enqueue(), curlyqueue_iterator_has_next(), and curlyqueue_iterator_has_prev().
int curlyqueue_iterator_has_next (curlyqueue_t * queue, except_t * e)
Tests if the current list element pointed at by the iterator has an element after it.
Exceptions:
empty_q if queue is empty
null_iter if iterator is null (use iter_reset to fix if q is non-empty)
Returns:
0 if queue does not have next
1 if queue does have next
See also:
curlyqueue_iterator_has_prev
Definition at line 254 of file curlyqueue.c.
int curlyqueue_iterator_has_prev (curlyqueue_t * queue, except_t * e)
Tests if the current list element pointed at by the iterator has an element before it.
Exceptions:
empty_q if queue is empty
null_iter if iterator is null (use iter_reset to fix if q is non-empty)
Returns:
0 if queue does not have prev
1 if queue does have prev
See also:
curlyqueue_iterator_has_next
Definition at line 284 of file curlyqueue.c.
void curlyqueue_iterator_jump_to_back (curlyqueue_t * queue)
Point the iterator at the back of the list.
Definition at line 177 of file curlyqueue.c.
Referenced by curlyqueue_delete_value_at_iterator(), and curlyqueue_enqueue().
void curlyqueue_iterator_jump_to_front (curlyqueue_t * queue)
Point the iterator at the front of the list.
Definition at line 184 of file curlyqueue.c.
void curlyqueue_iterator_step_backward (curlyqueue_t * queue, except_t * e)
Moves the iterator backward one item.
Exceptions:
null_iter if q iterator is null, which can happen if it has not yet been init'd, or if q is empty
Definition at line 213 of file curlyqueue.c.
Referenced by curlyqueue_delete_value_at_iterator().
void curlyqueue_iterator_step_forward (curlyqueue_t * queue, except_t * e)
Advances the queue iterator forward one element.
Exceptions:
null_iter if iterator is currently pointing at NULL, i.e. trying to access iter->next would be bad
Definition at line 196 of file curlyqueue.c.